### ISSUE TITLE
Does this patch enables vulkan on orange pi5?

### ISSUE THREAD

**Issue by Yusepp** [bbaranoff/bifrost_opi5_patch#1]
I've been playing with this powerful SBC for a while but I've been wondering why does the custom android based OS runs vulkan but other Linux distros don't. 

I'm running op5b on Ubuntu 22.04, OpenGL works nice but vulkan support could really help to achieve fast performance.

**Comment by bbaranoff** [comment]
Works in progress got a OPi5 and a 5Plus want hardware acceleration on glxinfo -B work on it since a while nothing useable maybe ubuntu https://github.com/Joshua-Riek/ubuntu-rockchip here but really not sure you are in the right place here but nothing useable i keep the issue open and hope i will be able to close it you are in the right place if i am able to enable vulkan one time or other

**Comment by bbaranoff** [comment]
https://xff.cz/kernels/6.6/
https://mega.nz/folder/j9QSDQSQ#6WpasOlbZYIInfw6yo4phQ/folder/LkgF1SoY
https://github.com/JeffyCN/mirrors/tree/libmali
I tried thoses but still no HW acceleration
If you have result can you tell me ?

**Comment by bbaranoff** [comment]
I also don't know how to install https://developer.arm.com/downloads/-/mali-drivers/valhall-kernel
Here you should be at my point

**Comment by bbaranoff** [comment]
README updated may you will have more luck

**Comment by bbaranoff** [comment]
https://github.com/Saikatsaha1996/mesa-Panfrost-G610
another fork of mesa but seems that G610 merged to master mesa but really not sure

**Comment by bbaranoff** [comment]
Short answer : no (but these is one of my goals)

**Comment by bbaranoff** [comment]
Closed

**Comment by bbaranoff** [comment]
Well the only way to have Vulkan Accelerated HW that I found now is to use Android 12 Image of official OrangePi5Plus downloads
